# This is a basic workflow to help you get started with Actions

name: Zigup CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Fetch zigup
        run: curl -L https://github.com/marler8997/zigup/releases/download/v2024_05_05/zigup-x86_64-linux.tar.gz | tar xz

      # Runs a single command using the runners shell
      - name: Make zigup executable
        run: chmod +x ./zigup
        
      # Runs a set of commands using the runners shell
      - name: Test with 0.13.0
        run: |
          ./zigup fetch 0.13.0
          ./zigup run 0.13.0 build test
          
      # Run with supported dev branch
      - name: Test with supported dev
        run: |
          ./zigup fetch 0.14.0-dev.1951+857383689
          ./zigup run 0.14.0-dev.1951+857383689 build test

      # Run with supported latest master
      - name: Test with latest master
        run: |
          ./zigup fetch master
          ./zigup run master build test
